<?php
           if(!isset($_GET["option"])){
            include ("dashboard_page_1.php");
           }else{
           switch($_GET["option"]) {
           case "main" : include ("dashboard_page_1.php");
           break;
           case "title-name" : include ("dashboard_page_2_masterdata_titlename.php");
           break;
           case "Vehicle-type" : include ("dashboard_page_2_masterdata_vehicle_type.php");
           break; 
           case "Energy-type" : include ("dashboard_page_2_masterdata_energy_type.php");
           break;
           case "study-type" : include ("dashboard_page_2_masterdata_type_study.php");
           break;
           case "subject-type" : include ("dashboard_page_2_masterdata_type_subject.php");
           break;
           case "teach-type" : include ("dashboard_page_2_masterdata_type_teach.php");
           break;
           case "trainer-type" : include ("dashboard_page_2_masterdata_type_trainer.php");
           break;
           case "province" : include ("dashboard_page_2_masterdata_province.php");
           break;
           case "amphur" : include ("dashboard_page_2_masterdata_amphur.php");
           break;
           case "district" : include ("dashboard_page_2_masterdata_district.php");
           break;
           case "district-edit" : include ("dashboard_page_2_masterdata_district_edit.php");
           break;
           case "zipcode" : include ("dashboard_page_2_masterdata_zipcode.php");
           break;
           case "zipcode-edit" : include ("dashboard_page_2_masterdata_zipcode_edit.php");
           break;
           case "country" : include ("dashboard_page_2_masterdata_country.php");
           break;
           case "nationality" : include ("dashboard_page_2_masterdata_nationality.php");
           break;
           case "career" : include ("dashboard_page_2_masterdata_career.php");
           break;
           case "income" : include ("dashboard_page_2_masterdata_income.php");
           break;
           case "Reason" : include ("dashboard_page_2_masterdata_reason.php");
           break;
           case "rangetime" : include ("dashboard_page_2_masterdata_rangetime.php");
           break;
           case "school-form-step-1" : include ("dashboard_page_3_school_form_1.php");
           break;
           case "school-form-step-2" : include ("dashboard_page_3_school_form_2.php");
           break;
           case "school-data" : include ("dashboard_page_3_school_data.php");
           break;
           case "school-edit" : include ("dashboard_page_3_school_edit.php");
           break;
           case "school-detail" : include ("dashboard_page_3_school_detail.php");
           break; 
           case "school-logo" : include ("dashboard_page_3_school_form_logo.php");
           break; 
           case "branch-data" : include ("dashboard_page_3_branch_data.php");
           break; 
           case "branch-data-edit" : include ("dashboard_page_3_branch_edit.php");
           break;  
           case "doc-data" : include ("dashboard_page_3_doc_data.php");
           break;
           case "course-group" : include ("dashboard_page_4_course_group_data.php");
           break;
           case "course-data" : include ("dashboard_page_4_course_data.php");
           break;   
           case "course-data-edit" : include ("dashboard_page_4_course_data_edit.php");
           break;   
           case "subject-data" : include ("dashboard_page_4_subject_data.php");
           break;     
           case "subject-data-edit" : include ("dashboard_page_4_subject_data_edit.php");
           break;  
           case "permission-theory-subjetct" : include ("dashboard_page_4_subject_permission_theory.php");
           break;
           case "form-course-step1" : include ("dashboard_page_4_subject_in_course_step_1.php");
           break;  
           case "form-course-step2" : include ("dashboard_page_4_subject_in_course_step_2.php");
           break;  
           case "course-data-detail" : include ("dashboard_page_4_subject_in_course_detail.php");
           break;  
           case "permission-Date" : include ("dashboard_page_4_table_Date.php");
           break; 
           case "permission-Date-edit" : include ("dashboard_page_4_table_Date_edit.php");
           break; 
           case "student-form" : include ("dashboard_page_5_student_form.php");
           break;  
           case "student-data" : include ("dashboard_page_5_student_data.php");
           break;  
           case "student-data-edit" : include ("dashboard_page_5_student_edit.php");
           break;  
           case "student-detail" : include ("dashboard_page_5_student_detail.php");
           break; 
           case "trainer-form" : include ("dashboard_page_6_trainer_form.php");
           break; 
           case "trainer-data" : include ("dashboard_page_6_trainer_data.php");
           break; 
           case "trainer-data-edit" : include ("dashboard_page_6_trainer_edit.php");
           break; 
           case "trainer-detail" : include ("dashboard_page_6_trainer_detail.php");
           break;
           case "authorities-data" : include ("dashboard_page_7_authorities_data.php");
           break;
           case "authorities-edit" : include ("dashboard_page_7_authorities_edit.php");
           break;
           case "authorities-data-general" : include ("dashboard_page_7_authorities_data_general.php");
           break;
           case "authorities-general-edit" : include ("dashboard_page_7_authorities_data_general_edit.php");
           break;
           case "group-user" : include ("dashboard_page_7_group_user.php");
           break;
           case "permission" : include ("dashboard_page_7_permission.php");
           break; 
           case "vehicle-form" : include ("dashboard_page_8_vehicle_form.php");
           break;
           case "vehicle-data" : include ("dashboard_page_8_vehicle_data.php");
           break;
           case "vehicle-data-edit" : include ("dashboard_page_8_vehicle_edit.php");
           break;
           case "vehicle-detail" : include ("dashboard_page_8_vehicle_detail.php");
           break;
           case "group-program" : include ("dashboard_page_9_group_program.php");
           break;
           case "program" : include ("dashboard_page_9_program.php");
           break; 
           case "DLT-form" : include ("dashboard_page_10_dlt_form.php");
           break; 
           case "DLT-data" : include ("dashboard_page_10_dlt_data.php");
           break; 
           case "DLT-edit" : include ("dashboard_page_10_dlt_edit.php");
           break;
           default : include ("dashboard_page_1.php");
            }
           }
           ?>